name: global_logger
description: global_logger package project
version: 2025.427.1713
homepage: 
repository: https://github.com/dart-pkg/global_logger

environment:
  sdk: ^3.7.2
dependencies:
  logger: ^2.5.0
dev_dependencies:
  lints: ^5.1.1
  output: ^2025.426.2027
  test: ^1.25.15
