name: global_logger
description: global_logger package project
version: 2025.427.1713
homepage: 
repository: https://github.com/dart-pkg/global_logger

environment:
  sdk: ^3.7.2
dependencies:
  logger: ^2.5.0
dev_dependencies:
  lints: ^6.0.0
  output: ^2025.502.1958
  test: ^1.26.2
